package com.fiap.hackathon.domain.question.enumerated;

public enum QuestionTopicEnum {

    HYPERTENSION,
    DIABETES,
    VACCINATION,
    EPIDEMIOLOGICAL_SURVEILLANCE,
    HEALTH_AND_ENVIRONMENTAL_SURVEILLANCE,
    PHARMACEUTICAL_ASSISTANCE,
    OCCUPATIONAL_HEALTH,
    INDIGENOUS_HEALTH,
    MANAGEMENT_AND_EDUCATION
}